config/routes.rb
TwitterSearch::Application.routes.draw do
  root 'tweets#show'
  post 'tweets/download_tweets', :as => 'download_tweets'
  get '/show' => 'tweets#show'

  post 'tweets/geolocation_search', :as => 'geolocation_search'
  get 'tweets/test', :as => 'test'
  get '/set_status' => 'tweets#set_status'
  match 'pdf_generate' => 'tweets#pdf_generate', via: [:get, :post]

end

app/models/count.rb
class Count < ActiveRecord::Base
end

app/models/layout.rb
class Layout < ActiveRecord::Base
end

app/models/pdf_generator.rb
class PdfGenerator

  def self.generate_pdf(tweets)
    pdf = Prawn::Document.new(:page_size => [800, 900], :page_layout => :landscape) do
      tweets.each_with_index do |tweet, j|
        #start_new_page(:size => [800, 900], :layout => :landscape) unless j == 0
        stroke do
          url = tweet.user.profile_image_url
          #uri = URI.encode(url)
          image open(url.to_s), :position => :left
          text tweet.user.name, :position => :left
          text tweet.text, :position => :right
        end
      end
    end
    pdf.render
  end

end

app/models/radius.rb
class Radius < ActiveRecord::Base
end

app/models/timeinterval.rb
class Timeinterval < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def get_client
  	@client = Twitter::REST::Client.new do |config|
  		config.consumer_key        = "5rHv2ZmtpLT5ANcRwP6HnWFnI"
  		config.consumer_secret     = "2HqQ1zcQDsCSauD5mKa8DDh6F8n6KXEH2vtw4m9MRBcs6QxBkB"
  		config.access_token        = "2381587561-PAfyvBC02Ne8E6x4YFrla4LIQUOuOb7An1qzpLM"
  		config.access_token_secret = "XrKEVZ6wZ9artQmn9GKYDiyZirB0yJf8GFJpqckzXdtCH"
  	end
  end
  
  def get_instagram
   @instagram = Instagram.configure do |config|
      config.client_id = "457fd8b4a868450082b201ff1e14e4eb"
      config.client_secret = "7f2447551e2946118814a656176340d8"
      
    end
  end 
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	require 'open-uri'
	require 'nokogiri'
	require 'cgi'

	def download_tweets
	
		count_record = Count.last
		count_status = count_record.update(:count => count_record.count + 1)
		@count_no = Count.last.count 
		html = render_to_string :partial => "test", :encoding => "UTF-8"
			#template_footer = File.read "#{Rails.root}/app/views/tweets/footer.html"
			

			pdf = PDFKit.new(html, :page_width =>'182', :page_height => '257', :margin_top => "0.2in", :margin_bottom => "0.2in", :margin_left => "0.2in", :margin_right => "0.2in",:header_right => ". [page]", :footer_html => "#{Rails.root}/app/views/tweets/footer.html" ) 
    		pdf.stylesheets << "#{Rails.root}/app/assets/stylesheets/test.css"
    		#pdf.stylesheets << "#{Rails.root}/app/assets/stylesheets/font.css"
    		pdf_path = Rails.root.join('tmp/pdf', "recent.pdf")
    		#pdf.to_file( "#{Rails.root}/tmp/pdf/recent.pdf")
    		
  			File.open(pdf_path, 'wb') do |file|
			file << pdf.to_pdf 
			
			end
			
			send_file pdf_path
	end

	def geolocation_search
        instagram_client = Instagram.client(:access_token => "1315053350.5b9e1e6.4eea0c712f504b22ab1be87b0e14b6a6")
        last_instagram_id = ''
        last_tweet = []
        location = []
		unless params[:commit] == "Stop"
			session[:start] = "on"
			Delayed::Job.where(:queue => "#{session[:key]}lat#{session[:latitude]}lng#{session[:longitude]}").delete_all
			get_client
			session[:geolocation] = params[:geolocation] 
			interval = "#{params[:search_data][:time_interval]}"
			session[:time_interval] = params[:search_data][:time_interval]
			#session[:time_interval] = 1
			time_delayed = Time.now.utc + session[:time_interval].to_i.minute - 45.seconds
			#time_delayed = Time.now.utc + 30.seconds
			radius = "#{params[:search_data][:radius]}"
			tweet_distance = Radius.find(radius).radius.to_i * 5
			@distance = "#{tweet_distance}km"
			session[:latitude] = params[:latitude].to_f.round(4).to_s
			session[:longitude] = params[:longitude].to_f.round(4).to_s
			geoloc = [session[:latitude], session[:longitude], @distance].join(',')
			session[:key] = params[:tweet]
			if session[:geolocation] == "on"
				@location = Geocoder.search("#{params[:latitude]}, #{params[:longitude]}")
				if session[:key].present?
					last_tweet = @client.search("##{session[:key]}", :result_type => "recent", :geocode => geoloc).take(1)
				else
					last_tweet = @client.search("", :result_type => "recent", :geocode => geoloc).take(1)						
				end
				#last_instagram_id = instagram_client.media_search(session[:latitude],session[:longitude], :distance=> 5,:min_timestamp => "1401526883", :count => 100)
				#last_instagram_id = last_instagram_id.pagination.min_tag_id
				last_instagram_id = ''
			else
			  begin
			    val = Geocoder.search(ip_address)
			   # val = Geocoder.search("182.64.56.7")
		        @lat_lon = [val[0].latitude, val[0].longitude]
		      rescue
			    @lat_lon = [48.8567,2.3508]
		      end
		      
		      @location = Geocoder.search("#{@lat_lon[0] }, #{@lat_lon[1] }")
		      last_instagram_id = instagram_client.tag_recent_media("#{session[:key]}", :count => 1) 	
			  last_instagram_id = last_instagram_id.pagination.min_tag_id
			  last_tweet = @client.search("##{session[:key]}", :result_type => "recent").take(1) if session[:twitter] == "on"
			end
			session[:last_tweet_id] = last_tweet[0].blank? ? '' : "#{last_tweet[0].id}"
			
		     Delayed::Job.enqueue(SearchJob.new(session[:geolocation],"#{session[:last_tweet_id]}", session[:instagram], session[:twitter], session[:time_interval], @distance,session[:latitude], session[:longitude], session[:key], last_instagram_id, @location[0].city, @location[0].country ), priority: 28,run_at: time_delayed, :queue => "#{session[:key]}lat#{session[:latitude]}lng#{session[:longitude]}")
			
		else
			Delayed::Job.where(:queue => "#{session[:key]}lat#{session[:latitude]}lng#{session[:longitude]}").delete_all
			session[:start] = "off"
		end
		redirect_to root_path
	end	


	def show
		session[:twitter] = "on"
		session[:instagram] = "on"
		ip_address = request.remote_ip
		begin
			val = Geocoder.search(ip_address)
			#val = Geocoder.search("182.64.56.7")
			@lat_lon = [val[0].latitude, val[0].longitude]
		rescue
			@lat_lon = [48.8567,2.3508]
		end
	end

	def set_status
		if session[params[:val]] == "on"
			session[params[:val]] = "off"
		else
			session[params[:val]] = "on"
		end
		
	end

	def pdf_generate
	count = Count.last.count
	file_path = Rails.root.join('public/pdf', "F0M0#{count}.pdf")
   	begin
   		send_file file_path
   	rescue Exception => e
   		redirect_to root_path
   	end
  end

end

	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterSearch</title>
  <%= stylesheet_link_tag    "application" , "https://api.tiles.mapbox.com/mapbox.js/v1.6.3/mapbox.css", "geolocation-search", "tweets", :media => "all" %>
  <%= javascript_include_tag "application", "https://api.tiles.mapbox.com/mapbox.js/v1.6.3/mapbox.js" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tweets/_tweets.html.erb
<div class="main">
	<ul class="tweets">
		<h1><%= @key %></h1>
			<% for count in 1..@tweets.count %>
				<% tweet = @tweets[count] %>
					<% unless tweet.blank? %>
						<% if tweet.created_at >= @time %>
							<li>
								<div class="imgb">
									<%= image_tag(tweet.user.profile_image_url) %>
										<span class="user_name">
											<%= tweet.user.name %>
										</span>
								</div>
								<div class="descrption">
									<p>
										<%= tweet.text %>
									</p>
									<span class="tweet_time">
										<%= tweet.created_at.strftime("%Y-%m-%d %I:%M:%S") %>
									</span>
								</div>
							</li>
						<% end %>
					<% end %>	
			<% end %>
	</ul>
	<ul class="tweets">
		<h1><%= @tag %></h1>
			<% for count in 1..@hashtags.count %>
				<% hashtag = @hashtags[count] %>
					<% unless hashtag.blank? %>
						<% if eval(hashtag.created_time) >= @time_instagram %>
							<li>
								<div class="imgb">
									<%= image_tag(hashtag.caption.from.profile_picture) %>
										<span class="user_name">
											<%= hashtag.user.full_name %>
										</span>
								</div>
								<div class="descrption">
									<p>
										<%= hashtag.caption.text %>
									</p>
									<span class="tweet_time">
										<%= Time.at(eval(hashtag.created_time)).strftime("%Y-%m-%d %I:%M:%S") %>
									</span>
								</div>
							</li>
						<% end %>
					<% end %>	
			<% end %>
	</ul>
</div>

app/views/tweets/index.html.erb
	<span class="search-btn">
	<%= link_to "Geolocation Search", {:controller => 'tweets' , :action => 'show'} %>
	</span>
<div class="search-block"> 
	<h1> Twitter/Instagram Search </h1>
		<%= form_tag download_tweets_path  do %>
			<div class="block-in">
			<%= label_tag :tweet, "Enter Keyword" %>
			<%= text_field_tag :tweet %>
			<%= submit_tag "Generate PDF" %>
		</div>
		<% end %>	

</div>

app/views/tweets/set_status.js.erb
val = "#<%= params[:val] %>_status"
$(val).html('/<%= session[params[:val]] %>')

app/views/tweets/show.html.erb
<div class="page-bg">
	<div class="box">
		<%= form_for(:search_data , :html => { :class => 'search_data' }, :url => {:action => "geolocation_search"})  do |f| %>
			<div class="header">
				<div class="heading">Choose your channels and search filters.</div>
					<div class="generator-interval">
						<span>Genrator interval:</span>
						<%= f.collection_select(:time_interval, Timeinterval.all, :time_interval_mins,:time_interval_mins) %>
					</div>
					<div class="layout-template">
						<span>Layout Template:</span>
						<%= f.collection_select(:layout, Layout.all, :id,:layouts) %>
					</div>
					<div class="generate">
						<div class="generate-in">
							<span>Generate!</span>
						<%= f.submit "Start", :class => 'start', :id => 'start' %>
                    
                    <%= f.submit "Stop", :class => 'stop', :name => "commit",:id => 'stop' %>
						</div>
					</div>
				</div>
				<div class="row">
					<span>Choose Channels:</span>
					<div class="leftside">			
						<%#= f.submit "Twitter" ,:class => 'twitter' %><%= link_to "Twitter", set_status_path(:val => "twitter"), :class => 'twitter', :remote => true %><small id="twitter_status">/<%= session[:twitter] %></small>
					</div>
					<%#= f.submit "Instagram" ,:class => 'instagram' %><%= link_to "Instagram", set_status_path(:val => "instagram"), :class => 'instagram', :remote => true %><small id = 'instagram_status'>/<%= session[:instagram] %></small>
				</div>
				<div class="leftcol">
					<span class="filter-hd">Filter via:</span>
					<div class="multiple-data">
						<span>#Hashtag /divide multiples with comes</span>
						<%= text_field_tag :tweet %>
					</div>
				</div>
				<div class="rightcol">
					<div class="geolocation-data">
						<span>Geolocation /Enter Lat.Long or drag & click the pin</span>
						<%= text_field_tag :latitude, @lat_lon[0] %>
						<%= text_field_tag :longitude, @lat_lon[1] %>
					</div>
			
					<div class="search-radius">
						<span>Search Radius</span>
							<%= f.collection_select(:radius, Radius.all, :id,:radius) %>
					</div>
					<div class = "geolocation_search">
						<span>Geolocation Search</span>
						<div class = "radio-label-on">
							<%= radio_button_tag 'geolocation', 'on' , :selected %> ON
						</div>
						<div class = "radio-label-off">
							<%= radio_button_tag 'geolocation', 'off' %> OFF
						</div>
					</div>
				</div>
				<div class="home_map">
					<div id="map">
					</div>
				</div>
			</div>
		<% end %>	
	</div>
</div>


<script>
	$(document).ready(function(){  
		var map = L.mapbox.map('map', 'vinaymehta.ibc7pbpm');
		map.setView(<%= @lat_lon %>, 14);
		var image_url =  '/assets/marker-icon.jpg';
    var sensor_icon = L.icon({
      iconUrl: image_url,
      iconSize: [35, 51],
      iconAnchor: [10, 38],
      popupAnchor: [0, -25]
    });
	  var marker = L.marker(
	  	["<%= @lat_lon[0] %>", "<%= @lat_lon[1] %>"],
	  	{
	  		icon: sensor_icon,
	  		draggable: true
	  	}
	  ).addTo(map);
	  var circle = L.circle(<%= @lat_lon %>, 1000, {draggable: true}).addTo(map);
	  marker.on('dragend', function(event){
	    var marker = event.target;
	    var position = marker.getLatLng();
	 
	    marker.setLatLng(new L.LatLng(position.lat, position.lng),{draggable:'true'});
	    circle.setLatLng(new L.LatLng(position.lat, position.lng),{draggable:'true'});
	    map.panTo(new L.LatLng(position.lat, position.lng))
			$(latitude).val(position.lat)
			$(longitude).val(position.lng)
		
	  });
	  $("#search_data_radius").change(function(){
	  	radius = ($(this).val())*1000;
	  	circle.setRadius(radius)
	  });

  });
</script>

<script>
<% unless session[:time_interval].blank? %>
//var counter = <%= session[:time_interval].to_i*60000+30000 %>;
var counter = <%= session[:time_interval].to_i*60000+30000 %>;
$( document ).ready(function() {
	window.setInterval( function() {
		sendgetreq();
	}, counter);
});
<% end %>
function sendgetreq()
{
	<% unless session[:start] == "off" %>
		window.location = 'pdf_generate.html';
	<% end %>
}

</script>
<script>
$(document).ready(function(){
	<% if session[:start] == "on" %>
      document.getElementById('start').disabled = 'true';
        $("#start").removeClass( "start" ).addClass( "start_status" );
     <% elsif session[:start] == nil %>
   		 $("#start").removeClass( "start_status" ).addClass( "start" );
   		 $("#stop").removeClass( "stop_status" ).addClass( "stop" );
     <% else session[:start] == "off" %>
        document.getElementById('stop').disabled = 'true';
        $("#stop").removeClass( "stop" ).addClass( "stop_status" );
    <% end %>	
});
    
   
</script>